SET NAMES utf8mb4;

INSERT INTO `jAagLSEY7_contacts` (`id`, `nom`, `prenom`, `email`, `telephone`, `categorie`, `sous_categorie`, `fonction`, `prioritaire`, `deleted`, `syndic`) VALUES
(2,	'STIEFEL',	'Anne',	'a.stiefel@begnins.ch',	'+41792297846',	'Begnins',	'Municipalité',	'SDIS, Administration générale, écoles, petite enfance, feu, pc, police',	1,	0,	1),
(3,	'GIROD',	'Christine',	'c.girod@gland.ch',	'+41791753579',	'Gland',	'Municipalité',	'Administration générale, ressources humaines, relations publiques et développement durable',	1,	0,	1),
(4,	'HAUSER',	'Pascal',	'p.hauser@begnins.ch',	'+41793166323',	'Begnins',	'Voirie',	'Chef de la voirie',	0,	0,	0),
(5,	'NICOLAS',	'Antoine',	'a.nicolas@begnins.ch',	'+41223662947',	'Begnins',	'Municipalité',	'Police des constructions, aménagement local',	0,	0,	0),
(6,	'CHYTIL',	'Robin ',	'r.chytil@begnins.ch',	'+41794093919',	'Begnins',	'Municipalité',	'Finances, forêts, cimetière, technologie, environnement, communication',	0,	0,	0),
(7,	'HALDEMANN',	'Éric',	'e.haldemann@begnins.ch',	'+41792727944',	'Begnins',	'Municipalité',	'Bâtiments, route, voirie',	0,	0,	0),
(8,	'MATHEY',	'Yves ',	'',	'+41793710508',	'Begnins',	'Concierge',	'L\\\\\\\'Esplanade',	0,	0,	0),
(9,	'LAFFELY',	'Bastien ',	'',	'+41792134012',	'Begnins',	'Concierge',	'Fleury',	0,	0,	0),
(10,	'Voirie',	'',	'',	'+41792134010',	'Begnins',	'Voirie',	'Piquet',	1,	0,	0),
(11,	'Groupe eau',	'',	'',	'+41223540490',	'Gland',	'SIE - Groupe Eau',	'Piquet',	1,	0,	0),
(12,	'Voirie',	'',	'',	'+41794691371',	'Gland',	'SIE - Voirie',	'Piquet',	1,	0,	0),
(13,	'ASP',	'',	'',	'+41792004565',	'Gland',	'Service de la population',	'Piquet',	1,	0,	0),
(14,	'Concierge',	'',	'',	'+41793116385',	'Gland',	'Concierge',	'Piquet',	1,	0,	0),
(15,	'CRETEGNY',	'Gérald ',	'g.cretegny@gland.ch',	'+41796923576',	'Gland',	'Municipalité',	'SDIS, Sécurité publique, population, transports publics',	1,	0,	0),
(16,	'MONNEY',	'Isabelle',	'i.monney@gland.ch',	'+41764223487',	'Gland',	'Municipalité',	'Affaires sociales, logement, culture, cultes, politique de la santé et des personnes âgées',	0,	0,	0),
(17,	'DAVOINE',	'Gilles ',	'g.davoine@gland.ch',	'+41792009351',	'Gland',	'Municipalité',	'Finances, économie, sports et domaines',	0,	0,	0),
(18,	'GENOUD',	'Thierry ',	't.genoud@gland.ch',	'+41792174462',	'Gland',	'Municipalité',	'Bâtiments et urbanisme',	0,	0,	0),
(19,	'WEBER',	'Jeannette ',	'j.weber@gland.ch',	'+41794789961',	'Gland',	'Municipalité',	'Accueil enfance, jeunesse, école',	0,	0,	0),
(20,	'GIRAUD-NYDEGGER',	'Christelle ',	'c.giraud-nydegger@gland.ch',	'+41791037821',	'Gland',	'Municipalité',	'Équipement et espaces verts, gestion des déchets et forêts',	0,	0,	0),
(21,	'Viquerat',	'Hervé ',	'herve@viquerat.net',	'+41794670014',	'SDIS',	'Etat-Major',	'QM',	0,	0,	0),
(22,	'GARNIER',	'Laetitia ',	'l.garnier@gland.ch',	'+41797642795',	'Gland',	'Service de la population',	'Cheffe du groupe Sécurité Publique',	0,	0,	0),
(23,	'BOUSSON',	'Sébastien ',	's.bousson@gland.ch',	'+41794489520',	'Gland',	'Service de la population',	'Assistant (ASP)',	0,	0,	0),
(24,	'FONTI',	'Julien ',	'j.fonti@gland.ch',	'+41797918396',	'Gland',	'Service de la population',	'Assistant (ASP)',	0,	0,	0),
(25,	'PERROUELLE',	'Loïc ',	'l.perrouelle@gland.ch',	'+41794298599',	'Gland',	'Service de la population',	'Assistant (ASP)',	0,	0,	0),
(26,	'RAVAL',	'François ',	'f.raval@gland.ch',	'+41793472062',	'Gland',	'Service de la population',	'Chef de service',	1,	0,	0),
(27,	'TRIJILLO',	'Ranfiss ',	'r.trujillo@gland.ch',	'+41223540435',	'Gland',	'SIE',	'Chef de service',	1,	0,	0),
(28,	'DÜRIG',	'Nicolas ',	'n.durig@gland.ch',	'+41794830566',	'Gland',	'SIE - Groupe Eau',	'Chef du groupe',	1,	0,	0),
(29,	'HÉRITIER',	'Yanick',	'y.heritier@gland.ch',	'+41223540430',	'Gland',	'SIE - Groupe Eau',	'Fontainier breveté',	1,	0,	0),
(30,	'PÉRILLAT',	'Michael',	'm.perillat@gland.ch',	'+41763992655',	'Gland',	'SIE - Groupe Eau',	'Surveillant de réseau',	0,	0,	0),
(31,	'HUBER',	'Cédric ',	'c.huber@gland.ch',	'+41797705444',	'Gland',	'SIE - Voirie',	'Chef du groupe',	1,	0,	0),
(32,	'ALLENBACH',	'Cyril ',	'c.allenbach@gland.ch',	'+41796363932',	'Gland',	'SIE - Espaces verts',	'Chef du groupe',	0,	0,	0),
(33,	'Déchetterie',	'',	'',	'+41796250510',	'Gland',	'SIE - Déchetterie',	'Piquet',	1,	0,	0),
(34,	'DUCRET',	'Eric',	'e.ducret@gland.ch',	'+41794486330',	'Gland',	'SBU',	'Chef de service',	1,	0,	0),
(35,	'CHEVALLEY',	'Steeve',	's.chevalley@gland.ch',	'+41794754315',	'Gland',	'SBU',	'Police des constructions',	0,	0,	0),
(36,	'THILLIER',	'Sébastien',	's.thillier@gland.ch',	'+41798204956',	'Gland',	'SBU',	'Technicien bâtiment',	0,	0,	0),
(37,	'CUSIN',	'Eric',	'e.cusin@gland.ch',	'+41793088812',	'Gland',	'SBU',	'Technicien bâtiment',	0,	0,	0),
(38,	'BARRAS',	'Daniel',	'',	'+41794693411',	'Gland',	'Concierge',	'Mauverney',	0,	0,	0),
(39,	'HENNY',	'Jean-Daniel',	'',	'+41796252539',	'Gland',	'Concierge',	'Grand-Champs',	0,	0,	0),
(40,	'SALLAZ',	'Thierry',	'',	'+41798485758',	'Gland',	'Concierge',	'',	0,	0,	0),
(41,	'AUBERT',	'Marcel',	'',	'+41794693687',	'Gland',	'Concierge',	'Les Tuillières',	0,	0,	0),
(42,	'BADEL',	'Michel',	'',	'+41794693930',	'Gland',	'Concierge',	'',	0,	0,	0),
(43,	'BASTOS',	'Nuno',	'',	'+41794692670',	'Gland',	'Concierge',	'',	0,	0,	0),
(44,	'CONCEICAO',	'Antonio',	'',	'+41794692670',	'Gland',	'Concierge',	'',	0,	0,	0),
(45,	'FREIRES DE MATOS',	'Daniel',	'',	'+41794693285',	'Gland',	'Concierge',	'',	0,	0,	0),
(46,	'BANDEIRA DA SILVA',	'Emanuel',	'',	'+41794691759',	'Gland',	'Concierge',	'',	0,	0,	0),
(47,	'ROY',	'Philippe',	'',	'+41794255421',	'Gland',	'Concierge',	'',	0,	0,	0),
(48,	'FAURE',	'Sandrine',	's.faure@gland.ch',	'+41796893554',	'Gland',	'SCAS',	'Chef de service',	1,	0,	0),
(49,	'LASSON',	'Mathieu',	'm.lasson@gland.ch',	'+41799610246',	'Gland',	'AEJE',	'Chef de service',	1,	0,	0),
(50,	'PÉCOUD',	'Sylvain',	'',	'',	'Le Vaud',	'Municipalité',	'Administration (gestion contractuelle  du personnel), Greffe, Contrôle des  habitants, Servi',	1,	0,	1),
(51,	'ROTZETTA',	'Pierre-Alain',	'',	'+41774092736',	'Le Vaud',	'Municipalité',	'SDIS, Bâtiments communaux (bâtiments communaux, église), Protection civile',	1,	0,	0),
(52,	'OLDACRE',	'Jonathan',	'',	'+41792024327',	'Le Vaud',	'Municipalité',	'Tourisme (loisirs, tourisme régional,  transports), Affaires culturelles,  Urbanisme (police des con',	0,	0,	0),
(53,	'HUMBERT',	'Sébastien',	'',	'+41797547566',	'Le Vaud',	'Municipalité',	'Terrains communaux (forêts, alpages,  terrains communaux, cours d’eau,  parcs et promenades), Voirie',	0,	0,	0),
(54,	'BECK',	'Nicolas',	'',	'',	'Le Vaud',	'Municipalité',	'Instruction publique (écoles, cantine,  service dentaire, patrouilles scolaires),  Structures social',	0,	0,	0),
(55,	'BARDET',	'Laurent',	'laurent.bardet@coinsins.ch',	'',	'Coinsins',	'Municipalité',	'Administration générale, Finances,  Domaines communaux, Conseil  régional, Eaux, Routes',	1,	0,	1),
(56,	'MARTINEZ ROBA',	'Gisèle',	'giselle.martinezr@coinsins.ch',	'+41792148921',	'Coinsins',	'Municipalité',	'SDIS, Espaces verts, Cimetière, Forêts /  Cours d\'eau, Gestion des déchets',	1,	0,	0),
(57,	'PERROSET',	'Marlyse',	'marlyse.perroset@coinsins.ch',	'',	'Coinsins',	'Municipalité',	'AISE, Petite enfance, Affaires sociales  ( ARAS ), Aînés, Culte',	0,	0,	0),
(58,	'CERATO',	'Serge',	'serge.cerato@coinsin.ch',	'+41792929268',	'Coinsins',	'Municipalité',	'Bâtiments communaux,  Manifestations / Sociétés,  Aménagement du territoire, Services  industriels',	0,	0,	0),
(59,	'MERMOUD',	'Olivier',	'olivier.mermoud@coinsins.ch',	'',	'Coinsins',	'Municipalité',	'Police des constructions, Police,  Protection civile, Cantine scolaire',	0,	0,	0),
(60,	'JEANRENAUD',	'Valérie',	'',	'',	'Burtigny',	'Municipalité',	'Administration générale, Région ',	1,	0,	1),
(61,	'COTTIER',	'Sébastien',	'',	'+41774161318',	'Burtigny',	'Municipalité',	'SDIS, Eaux, Déchets (SADEC), Protection ',	1,	0,	0),
(62,	'THÉVENOT',	'Philippe',	'pthevenot@begnins.ch',	'+41788185246',	'Begnins',	'Municipalité',	'Service des eaux et épuration, ',	0,	0,	0),
(63,	'JACCARD',	'Moya',	'',	'',	'Burtigny',	'Municipalité',	'Bâtiments, Ecoles et accueil de jour  (AISE, RAT), Culte et paroisse,  Jeunesse, Social et Santé pub',	0,	0,	0),
(64,	'ZANON',	'Basak',	'',	'',	'Burtigny',	'Municipalité',	'Constructions et urbanisme, Routes et  mobilité, Domaines publiques,  Informatique, Tourisme',	0,	0,	0),
(65,	'REDARD',	'Maude',	'',	'',	'Burtigny',	'Municipalité',	'Espaces verts, Cimetière, Forêts,  Environnement',	0,	0,	0),
(66,	'SALAMIN',	'Antonella',	'antonella.salamin@vich.ch',	'+41794578658',	'Vich',	'Municipalité',	'Administration générale et relations  extérieures, finances, écoles et petite  enfance, ci',	1,	0,	1),
(67,	'BISSAT',	'Jean-Claude',	'jean-claude.bissat@vich.ch',	'+41792051488',	'Vich',	'Municipalité',	'SDIS, Bâtiments, voirie, culture et  manifestations',	1,	0,	0),
(68,	'MUNDLER',	'Philippe',	'philippe.mundler@vich.ch',	'+41792127742',	'Vich',	'Municipalité',	'Police des constructions, affaires  régionales et sociétés locales, police  générale, informatique',	0,	0,	0),
(69,	'STOECKLIN',	'Richard',	'richard.stoecklin@vich.ch',	'+41794013212',	'Vich',	'Municipalité',	'Centre de tri et gestion des déchets,  alimentation en eau, protection civile,  sport',	0,	0,	0),
(70,	'WUERSCH',	'Carol',	'carol.wuersch@vich.ch',	'+41789459394',	'Vich',	'Municipalité',	'Urbanisme et aménagement du  territoire, routes et évacuation des  eaux, environnement et nature,  a',	0,	0,	0),
(71,	'PITTET',	'Sonia',	'sonia.pittet@bassins.ch',	'',	'Bassins',	'Municipalité',	'Administration Générale, Alpages, Cimetière – Eglise – Paroisse, Parc Jura Vaudois, Police des Constructions – STI – Urbanisme',	1,	0,	1),
(72,	'DUNAND',	'André',	'andre.dunand@bassins.ch',	'',	'Bassins',	'Municipalité',	'SDIS, Forêts – Camping, Routes – Sécurité  routière',	1,	0,	0),
(73,	'CURRAT',	'Denis',	'denis.currat@bassins.ch',	'',	'Bassins',	'Municipalité',	'Eaux – Epuration, Energie, Finances',	0,	0,	0),
(74,	'GUIGNARD-PUIDOUX',	'Nathalie',	'nathalie.guignard-pidoux@bassins.ch',	'',	'Bassins',	'Municipalité',	'Affaires sociales et Plan canicule,  Bâtiments communaux, Parcs et  promenades – Places de jeux, Pet',	0,	0,	0),
(75,	'MAZZARIOL',	'Marc',	'marc.mazzariol@bassins.ch',	'',	'Bassins',	'Municipalité',	'Déchetterie ,Ecoles – Patrouilleurs - Transports scolaires, Piscine, Police,  Transition énergétique',	0,	0,	0);